version: '3'

services:
  formdang-api-spring:
    image: ${DOCKER_IMAGE_NAME}
    container_name: ${DOCKER_CONTAINER_NAME}
    ports:
      - "${PORT}:${PORT}"
      - "35010:35010"
    networks:
      - formdang-network
      - zabbix-net
    volumes:
      -  logs:/logs
    environment:
      - ACTIVE_PROFILE=${PROFILE}
    restart: unless-stopped

networks:
  formdang-network:
    external: true
  zabbix-net:
    external: true

volumes:
  logs:
    external: true
