# LOCAL
---
spring:
  config:
    activate:
      on-profile: local

aws:
  s3:
    region: ENC(iF1dl+uXxelMbqT+8JmmE4BltPPLlRFEPDm9wOxgukyZx5KhSP793rQtBlEaI+b+)
    access-key: ENC(KCheOCnZCC3cW5H54f0YSFqm3NPs7JJ+EkDDWRK1TB3wWEo1MkDp21QEKPZRgYJN9a25bv/Pn2Vkuzac2AHnvw==)
    secret-key: ENC(zN7RFA2wnCIYvPfcz2SL5ZqgRrVFooTt9bNgbODFwiirtbcNYNG2/S+6fdSfxpeSPemKo+STljUxWHkSH9zISXVxJYJ1RjkWNESqa431wo0=)
    buket: ENC(JtR+UsfqIaEDX/M+OKRjBO/IrkL+LLulF1eQ45YVrEzL1JLay4wb93ivH4t3teJz)
    host: ENC(8TS6H/vrd+fLMN2PvaVgDnTE2OnioGJay/yxOIyqiLakTXO66AtToVFjX5YR+a3LsNJjwN8l6ow8ggpymRHSNEi71CKEM21mc5Ej4Db233H3oMtSN+V7CiHSzLcLYW7z)

# TEST
---
spring:
  config:
    activate:
      on-profile: test

# PROD
---
spring:
  config:
    activate:
      on-profile: prod