spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    open-in-view: false
    show-sql: true
  data:
    redis:
      repositories:
        enabled: false
cloud:
  aws:
    s3:
      bucket: formmaster-s3
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    host: https://s3.ap-northeast-2.amazonaws.com/formmaster-s3/


# LOCAL
---
spring:
  config:
    activate:
      on-profile: local

# TEST
---
spring:
  config:
    activate:
      on-profile: test


# PROD
---
spring:
  config:
    activate:
      on-profile: prod