server:
  shutdown: graceful
  servlet:
    context-path: /

spring:
  profiles:
    active: local
    include:
      - core
  application:
    name: web-api

file:
  size:
    image: 3145728 # 3 * 1024 * 1024
    video: 104857600 # 100 * 1024 * 1024
    replay: 52428800 # 50 * 1024 * 1024