spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    generate-ddl: false # 자동으로 DDL 생성 해주는 기능 OFF
    hibernate:
      ddl-auto: none # 엔티티만 등록해놓으면 DDL(Data Definition Language)을 자동으로 작성하여 테이블을 생성하거나 수정해주는 기능 OFF
    open-in-view: false # 영속성 컨테이너의 트랜잭션 범위를 넘어 레이어까지 유지 (api: 클라이어언트에 응답 될떄까지, view: view 페이지 랜더링까지 커넥션이 살아있음, off 시 lazy loading 트랜잭션 범위 밖에서 시도시 exception 발생)
    show-sql: false  # 콘솔 로그 출력
  data:
    redis:
      repositories:
        enabled: false # redisRepository 사용하지 않을 경우  off

# LOCAL
---
spring:
  config:
    activate:
      on-profile: local

# TEST
---
spring:
  config:
    activate:
      on-profile: test


# PROD
---
spring:
  config:
    activate:
      on-profile: prod