server:
  port: 12001
  shutdown: graceful
  servlet:
    context-path: /api/sp # nginx prefix location으로 잡혀있음

spring:
  profiles:
    active: local
    include: # 다른 모듈 yml 사용을 위해 적용
      - common # common-web
      - dao # core-web
      - core # domain-core
    group: # active 레벨에 따른 로깅 레벨 설정
      local:
        - console-logging # 콘솔 로깅만 사용
      test:
        - console-logging
        - file-logging # 파일 로깅 사용
      prod:
        - console-logging
        - file-logging # 파일 로깅 사용
  application:
    name: web-api
  jackson:
    time-zone: Asia/Seoul
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size:  30MB

file:
  size:
    image: 3145728 # 3 * 1024 * 1024