server:
  port: 12001
  shutdown: graceful
  servlet:
    context-path: /api/sp
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

spring:
  profiles:
    active: local
    include:
      - core
      - dao
      - middleware
  application:
    name: web-api
  jackson:
    time-zone: Asia/Seoul
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size:  30MB

file:
  size:
    image: 3145728 # 3 * 1024 * 1024

token:
  access-key: r5ZW27aCNHCnabMd2sQ534mnuIrHAcnshjGXBadqQnpiKKfv2sdAsa7fx4hVSJU5


#LOG
logging:
  level:
    root: info
    jdbc.sqlonly: debug
    jdbc.audit: debug
    jdbc.resultset: debug
    jdbc.connection: debug
    http.logging: debug
    org.springframework.test: warn
    com.amazonaws.util.EC2MetadataUtils: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%-5level] [%thread] [%logger{0}:%line] [%X{request_id:-startup}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%-5level] [%thread] [%logger{0}:%line] [%X{request_id:-startup}] - %msg%n"
  logback:
    rolling policy:
      max-history: 365
      max-file-size: 100MB