google:
  auth:
    url: https://oauth2.googleapis.com
    scope: profile,email,openid
  login:
    url: https://accounts.google.com
  client:
    id: ENC(2PcEUWW+zVuotleTkk2sPWBU3PiDKChw6pclPAJZiJkiiHGIMnkTJaP2IiafOGIVTTAaND7Bts5thDBeB0ZaoWj2pYa57ae/Hvt0Qsd3YPc=)
  secret: ENC(kV1a9mkN5FuK3/ecNmAhBVmH5dHQ6LVxvNn3Xamqy0GOonCODfeh+zZ5SpnsmmRrfzQuiinKkvASst72iGQTE+W53JecZpqiZm7Fxm36bgA=)

kakao:
  auth:
    url: https://kapi.kakao.com
  login:
    url: https://kauth.kakao.com
  client:
    id: ENC(3honbmeuFerE4FqbWv7yEEn8Mi4DdS5EQthLoAnwW+xvYwWiB1J2ooDXI+vf/8xcM8kqJZuH2nAQbv2LplaAVkV1oUbRCZbEdOFgAoGy0yM=)
  secret: ENC(v5lcLr9aytE1xqbkdKYO2tW3EGN1dAG0Z/2j+B1q/AfkDb2CiwGLkCDwa21Q6ZgueOP2m3SFDSGEOzJ9ENGsQANI4C+zGUUONiUJwHVMwVk=)

# LOCAL
---
spring:
  config:
    activate:
      on-profile: local

formdang:
  auth-issue:
    url: http://localhost:22081/auth/sp/issue # app 인증 서버 토큰 발급 요청 URL
  fail-login: http://localhost:63342/formdang-publishing/admin/login.html
  success-login: http://localhost:63342/formdang-publishing/admin/index.html
  success-paper-login: http://localhost:63342/formdang-publishing/web/paper.html
  secret-key: ENC(+vT6/Edj0qUG0eVWSFX8KgPhVHcDSMdmsTqv86f55LUa/qD1ZVUIV+cucA2ofkcAtMjixtg5j0v8tgWEs0JQva3G2O33vRYeIPhg08cVsyjlf4Sq0+039RITwiuYgd649IN/CGjJ9LiXVpRtF7hu4Q==)

google:
  redirect:
    uri: http://localhost:12001/api/sp/public/google/login/callback # 구글 일반 로그인 콜백 URL
    paper_uri: http://localhost:12001/api/sp/public/google/login/paper/callback # 구글 유저 작성 Form 화면 로그인 콜백 URL

kakao:
  redirect:
    login:
      uri: http://localhost:12001/api/sp/public/kakao/login/callback # 카카오 일반 로그인 콜백 URL
      paper_uri: http://localhost:12001/api/sp/public/kakao/login/paper/callback # 카카오 유저 작성 Form 화면 로그인 콜백 URL

# TEST
---
spring:
  config:
    activate:
      on-profile: test

formdang:
  auth-issue:
    url: http://formdang-sp-auth:22081/auth/sp/issue # app 인증 서버 토큰 발급 요청 URL (docker network)
  fail-login: https://formdang.com/admin/login.html
  success-login: https://formdang.com/admin/index.html
  success-paper-login: https://formdang.com/web/paper.html
  secret-key: ENC(+vT6/Edj0qUG0eVWSFX8KgPhVHcDSMdmsTqv86f55LUa/qD1ZVUIV+cucA2ofkcAtMjixtg5j0v8tgWEs0JQva3G2O33vRYeIPhg08cVsyjlf4Sq0+039RITwiuYgd649IN/CGjJ9LiXVpRtF7hu4Q==)

google:
  redirect:
    uri: http://formdang-api.com/api/sp/public/google/login/callback # 구글 일반 로그인 콜백 URL
    paper_uri: http://formdang-api.com/api/sp/public/google/login/paper/callback # 구글 유저 작설 Form 화면 로그인 콜백 URL

kakao:
  redirect:
    login:
      uri: http://formdang-api.com/api/sp/public/kakao/login/callback # 카카오 일반 로그인 콜백 URL
      paper_uri: http://formdang-api.com/api/sp/public/kakao/login/paper/callback # 카카오 유저 작성 Form 화면 로그인 콜백 URL

# PROD
---
spring:
  config:
    activate:
      on-profile: prod

formdang:
  auth-issue:
    url: http://formdang-sp-auth:22081/auth/sp/issue # app 인증 서버 토큰 발급 요청 URL (docker network)
  fail-login: https://formdang.com/admin/login.html
  success-login: https://formdang.com/admin/index.html
  success-paper-login: https://formdang.com/web/paper.html
  secret-key: ENC(+vT6/Edj0qUG0eVWSFX8KgPhVHcDSMdmsTqv86f55LUa/qD1ZVUIV+cucA2ofkcAtMjixtg5j0v8tgWEs0JQva3G2O33vRYeIPhg08cVsyjlf4Sq0+039RITwiuYgd649IN/CGjJ9LiXVpRtF7hu4Q==)

google:
  redirect:
    uri: http://formdang-api.com/api/sp/public/google/login/callback # 구글 일반 로그인 콜백 URL
    paper_uri: http://formdang-api.com/api/sp/public/google/login/paper/callback # 구글 유저 작설 Form 화면 로그인 콜백 URL

kakao:
  redirect:
    login:
      uri: http://formdang-api.com/api/sp/public/kakao/login/callback # 카카오 일반 로그인 콜백 URL
      paper_uri: http://formdang-api.com/api/sp/public/kakao/login/paper/callback # 카카오 유저 작성 Form 화면 로그인 콜백 URL