name: CI-CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  S3_BUCKET_NAME: formdang-deploy-s3
  RESOURCE_PATH: ./formdang-api/src/main/resources/application.yaml
  CODE_DEPLOY_APPLICATION_NAME: formdang
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: formdang-api
  PROJECT_DIR: formdang-api
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          distribution: 'temurin'

#      - name: Set yaml file
#        uses: microsoft/variable-substitution@v1
#        with:
#          files: ${{ env.RESOURCE_PATH }}
#        env:
#          override.value: ${{ secrets.DI_FROM_SECRET }}

#      - name: Cache Maven packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true -B package --file ${{ env.PROJECT_DIR }}/pom.xml

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip ./${{ env.PROJECT_DIR }}/target/*.jar ./appspec.yml ./deploy.sh ./DockerFile
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

      - name: deploy with AWS codeDeploy
        run: | 
          aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
