name: CI-CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
#
      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true -B package --file ./pom.xml

      - name: Docker Build Image
        run: docker build -t formdang .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: form.master.prod@gmail.com
          password: formmaster1qaz!

      - name: build and release to DockerHub
        env:
          NAME: formdang
          REPO: was
        run : |
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest
