name: CI-CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Cache Maven
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Maven Package
      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true -B package --file ./pom.xml

      # Docker Image Build
      - name: Docker Build Image
        run: docker build -t ${{ secrets.DOCKER_HUB_REPO }} .

      # Docker Hub Login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Docker Hub 이미지 push
      - name: Build and release to DockerHub
        env:
          NAME: ${{ secrets.DOCKER_HUB_NAME }}
          REPO: ${{ secrets.DOCKER_HUB_REPO }}
        run : |
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest

  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker rm -f $(docker ps -qa)
            docker rmi $NAME/$REPO
            docker pull $NAME/$REPO
            docker run -d --name formdang-was -p 12001:12001 --network nginx_server-connection -v formdang-was-log:/app/logs -e ACTIVE_PROFILE=test $NAME/$REPO